#!/bin/sh
set -e
case "$1" in
    remove|purge)
        rm -f /usr/lib/systemd/system/rustdeskmcp.service
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload
        fi
        ;;
esac
if [ "$1" = purge ]; then
    rm -rf /root/.config/rustdeskmcp
fi
