#!/bin/sh
set -e
case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop rustdeskmcp.service || true
            if [ "$1" = remove ]; then
                systemctl disable rustdeskmcp.service || true
            fi
        fi
        ;;
esac
